import { defineProperties } from '@vanilla-extract/sprinkles';
import { vars } from '../theme/index.css';
import { breakpoints } from './breakpoints.css';

export const border = defineProperties({
  ...breakpoints,
  properties: {
    borderRadius: ['100%'],
    borderColor: {
      'primary-light': vars.palette.primary.light,
      'primary-main': vars.palette.primary.main,
      'primary-dark': vars.palette.primary.dark,
      'primary-contrastText': vars.palette.secondary.contrastText,
      'secondary-light': vars.palette.secondary.light,
      'secondary-main': vars.palette.secondary.main,
      'secondary-dark': vars.palette.secondary.dark,
      'secondary-contrastText': vars.palette.secondary.contrastText,
      'text-primary': vars.palette.lightMode.text.primary,
      'text-secondary': vars.palette.lightMode.text.secondary,
    },
    border: {
      1: '1px solid',
    },
    borderTop: {
      1: '1px solid',
    },
    borderRight: {
      1: '1px solid',
    },
    borderBottom: {
      1: '1px solid',
    },
    borderLeft: {
      1: '1px solid',
    },
    textDecoration: {
      'primary-light': `underline ${vars.palette.primary.light}`,
      'primary-main': `underline ${vars.palette.primary.main}`,
      'primary-dark': `underline ${vars.palette.primary.dark}`,
      'primary-contrastText': `underline ${vars.palette.secondary.contrastText}`,
      'secondary-light': vars.palette.secondary.light,
      'secondary-main': vars.palette.secondary.main,
      'secondary-dark': vars.palette.secondary.dark,
      'secondary-contrastText': vars.palette.secondary.contrastText,
      'text-primary': `underline ${vars.palette.lightMode.text.primary}`,
      'text-secondary': vars.palette.lightMode.text.secondary,
    },
    textAlign: ['right', 'left', 'center'],
    fontWeight: ['bold', 'border'],
    cursor: ['pointer', 'default'],
    fontSize: {
      h1: vars.typography.h1.fontSize,
      h2: vars.typography.h2.fontSize,
      h3: vars.typography.h3.fontSize,
      h4: vars.typography.h4.fontSize,
      h5: vars.typography.h5.fontSize,
      h6: vars.typography.h6.fontSize,
      subtitle1: vars.typography.subtitle1.fontSize,
      subtitle2: vars.typography.subtitle2.fontSize,
      body1: vars.typography.body1.fontSize,
      body2: vars.typography.body2.fontSize,
      button: vars.typography.button.fontSize,
      caption: vars.typography.caption.fontSize,
      overline: vars.typography.overline.fontSize,
    },
    lineHeight: {
      h1: vars.typography.h1.lineHeight,
      h2: vars.typography.h2.lineHeight,
      h3: vars.typography.h3.lineHeight,
      h4: vars.typography.h4.lineHeight,
      h5: vars.typography.h5.lineHeight,
      h6: vars.typography.h6.lineHeight,
      subtitle1: vars.typography.subtitle1.lineHeight,
      subtitle2: vars.typography.subtitle2.lineHeight,
      body1: vars.typography.body1.lineHeight,
      body2: vars.typography.body2.lineHeight,
      button: vars.typography.button.lineHeight,
      caption: vars.typography.caption.lineHeight,
      overline: vars.typography.overline.lineHeight,
    },
    letterSpacing: {
      h1: vars.typography.h1.letterSpacing,
      h2: vars.typography.h2.letterSpacing,
      h3: vars.typography.h3.letterSpacing,
      h4: vars.typography.h4.letterSpacing,
      h5: vars.typography.h5.letterSpacing,
      h6: vars.typography.h6.letterSpacing,
      subtitle1: vars.typography.subtitle1.letterSpacing,
      subtitle2: vars.typography.subtitle2.letterSpacing,
      body1: vars.typography.body1.letterSpacing,
      body2: vars.typography.body2.letterSpacing,
      button: vars.typography.button.letterSpacing,
      caption: vars.typography.caption.letterSpacing,
      overline: vars.typography.overline.letterSpacing,
    },
    overflowX: ['scroll', 'hidden'],
    overflowY: ['scroll', 'hidden'],
    overflow: ['scroll', 'hidden'],
    listStyle: ['none', 'inside'],
    wordBreak: ['break-all'],
    wordWrap: ['break-word'],
    whiteSpace: ['pre-wrap'],
    visibility: ['hidden'],
  },
});
